[project]
name = "blog-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.83",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "mangum>=0.22.0",
    "pip>=26.2.1",
    "pymysql>=1.2.0",
    "sqlmodel>=0.0.39",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
